// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingNew.Web.Data;

namespace ParkingNew.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200410220441_addrelacionn")]
    partial class addrelacionn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingNew.Web.Data.Entities.Parking", b =>
                {
                    b.Property<int>("Id_Parking")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion_Parking")
                        .IsRequired();

                    b.Property<int>("Disponible_Parking");

                    b.Property<bool>("Estado_Parking");

                    b.Property<string>("Imagen_Parking");

                    b.Property<double>("Latitud_Parking");

                    b.Property<double>("Longitud_Parking");

                    b.Property<string>("Nombre_Parking")
                        .IsRequired();

                    b.Property<decimal>("Precio_Parking")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Parking");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("ParkingNew.Web.Data.Entities.User", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido_User")
                        .IsRequired();

                    b.Property<string>("Nombre_User")
                        .IsRequired();

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(6);

                    b.Property<int>("Telefono");

                    b.HasKey("Id_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ParkingNew.Web.Data.Entities.UserParking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Parking");

                    b.Property<int>("Id_User");

                    b.HasKey("Id");

                    b.HasIndex("Id_Parking");

                    b.HasIndex("Id_User");

                    b.ToTable("UserParkings");
                });

            modelBuilder.Entity("ParkingNew.Web.Data.Entities.UserParking", b =>
                {
                    b.HasOne("ParkingNew.Web.Data.Entities.Parking", "Parking")
                        .WithMany("UserParkings")
                        .HasForeignKey("Id_Parking")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ParkingNew.Web.Data.Entities.User", "User")
                        .WithMany("UserParkings")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
